#!/bin/zsh
set -euo pipefail

SCRIPT_PATH="${0:A}"
SITE_DIR="${SCRIPT_PATH:h:h}"
WORKSPACE_DIR="${SITE_DIR:h}"
STATE_DIR="${QUANTUM_STORAGE_AUTOMATION_STATE:-/Users/xiangrikui/Library/Application Support/quantum-storage-review-updater}"
CODEX_BIN="${CODEX_BIN:-/opt/homebrew/bin/codex}"
NODE_BIN="${NODE_BIN:-/opt/homebrew/bin/node}"
GIT_BIN="${GIT_BIN:-/usr/bin/git}"

AUTOMATION_DIR="$SITE_DIR/automation"
PROMPT_FILE="$AUTOMATION_DIR/daily-update.prompt.md"
ZOTERO_SCANNER="$AUTOMATION_DIR/scan-zotero-library.mjs"
LOCK_DIR="$STATE_DIR/run.lock"
RUN_LOG="$STATE_DIR/runner.log"
LAST_RESEARCH_DATE="$STATE_DIR/last-research-date"
BASELINE_SNAPSHOT="$STATE_DIR/zotero/last-research-snapshot.json"
TODAY=$(/bin/date +%F)

mkdir -p "$STATE_DIR/reports" "$STATE_DIR/zotero"
exec >> "$RUN_LOG" 2>&1
print -r -- "[$(/bin/date '+%Y-%m-%d %H:%M:%S %z')] research-only updater started"

if [[ "${1:-}" == "--dry-run" ]]; then
  print -r -- "site=$SITE_DIR"
  print -r -- "workspace=$WORKSPACE_DIR"
  print -r -- "state=$STATE_DIR"
  print -r -- "mode=research-only; website edits and publication are disabled"
  print -r -- "zotero_baseline=$BASELINE_SNAPSHOT"
  print -r -- "interval=86400 seconds (LaunchAgent may poll more frequently)"
  exit 0
fi

if [[ -f "$LAST_RESEARCH_DATE" ]] && [[ "$(<"$LAST_RESEARCH_DATE")" == "$TODAY" ]]; then
  print -r -- "[$TODAY] research report already completed; exiting"
  exit 0
fi

if [[ -d "$LOCK_DIR" ]]; then
  old_pid=""
  [[ -f "$LOCK_DIR/pid" ]] && old_pid="$(<"$LOCK_DIR/pid")"
  if [[ -n "$old_pid" ]] && /bin/kill -0 "$old_pid" 2>/dev/null; then
    print -r -- "another updater is running (pid $old_pid); exiting"
    exit 0
  fi
  [[ -f "$LOCK_DIR/pid" ]] && /bin/rm "$LOCK_DIR/pid"
  /bin/rmdir "$LOCK_DIR" 2>/dev/null || true
fi

if ! /bin/mkdir "$LOCK_DIR" 2>/dev/null; then
  print -r -- "could not acquire updater lock; exiting"
  exit 0
fi
print -r -- "$$" > "$LOCK_DIR/pid"
cleanup() {
  [[ -f "$LOCK_DIR/pid" ]] && /bin/rm "$LOCK_DIR/pid"
  /bin/rmdir "$LOCK_DIR" 2>/dev/null || true
}
trap cleanup EXIT

if [[ -z "${CODEX_HOME:-}" ]]; then
  print -r -- "CODEX_HOME is not set; scheduled Codex identity is undefined"
  exit 1
fi
if [[ ! -x "$CODEX_BIN" || ! -x "$NODE_BIN" ]]; then
  print -r -- "required Codex or Node executable is missing"
  exit 1
fi
if [[ ! -d "$SITE_DIR/.git" ]]; then
  print -r -- "canonical site Git repository is missing: $SITE_DIR"
  exit 1
fi
if [[ ! -r "$PROMPT_FILE" || ! -r "$ZOTERO_SCANNER" ]]; then
  print -r -- "research support files are missing or unreadable"
  exit 1
fi

dirty="$($GIT_BIN -C "$SITE_DIR" status --porcelain --untracked-files=all | /usr/bin/grep -v '^?? \.DS_Store$' || true)"
if [[ -n "$dirty" ]]; then
  print -r -- "canonical site has uncommitted changes; refusing to run scheduled research"
  print -r -- "$dirty"
  exit 1
fi

QUANTUM_ZOTERO_BASELINE_FILENAME="last-research-snapshot.json" \
  "$NODE_BIN" "$ZOTERO_SCANNER" "$STATE_DIR"

report_tmp="$STATE_DIR/reports/.${TODAY}.$$"
report_final="$STATE_DIR/reports/${TODAY}.md"
if ! "$CODEX_BIN" exec \
    --cd "$SITE_DIR" \
    --sandbox read-only \
    --search \
    --ephemeral \
    --add-dir "$STATE_DIR" \
    - < "$PROMPT_FILE" > "$report_tmp"; then
  /bin/rm -f "$report_tmp"
  print -r -- "Codex research task failed; no report checkpoint advanced"
  exit 1
fi

if [[ ! -s "$report_tmp" ]]; then
  /bin/rm -f "$report_tmp"
  print -r -- "Codex returned an empty research report"
  exit 1
fi

report_with_header="$STATE_DIR/reports/.${TODAY}.$$.md"
{
  print -r -- "# Quantum-storage-review research scan — $TODAY"
  print -r -- ""
  print -r -- "This report was generated by the Codex CLI research-only runner. The website repository was not edited, committed, or pushed."
  print -r -- ""
  /bin/cat "$report_tmp"
} > "$report_with_header"
/bin/mv -f "$report_with_header" "$report_final"
/bin/rm -f "$report_tmp"

snapshot_tmp="$STATE_DIR/zotero/.last-research-snapshot.$$"
/bin/cp "$STATE_DIR/zotero/current-snapshot.json" "$snapshot_tmp"
/bin/mv -f "$snapshot_tmp" "$BASELINE_SNAPSHOT"
date_tmp="$STATE_DIR/.last-research-date.$$"
print -r -- "$TODAY" > "$date_tmp"
/bin/mv -f "$date_tmp" "$LAST_RESEARCH_DATE"
print -r -- "[$TODAY] research-only updater completed; review $report_final before publishing"

